New API that returns reports
Reveal-IQ/MEMS pull request #138
Opened 2024-04-30 07:25 UTC by yousiefc

# PR Description

Added API to generate reports 

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?
API tester client

## Screenshots (if appropriate):

2024-04-30 11:10 UTC, akshaypuli requested changes
Thank You for the PR! Looks great! Just a few comments. Could you also upload the YAML test file?

2024-04-30 11:10 UTC, akshaypuli commented on src/api/api/BIOMD/BIOMD.js
> +module.exports.RECORDS = async function (req, dbClient) {
Could we change the API to be called GET_REPORTS

2024-04-30 11:10 UTC, akshaypuli commented on src/api/api/BIOMD/BIOMD.js
> +    var find = Object.assign({}, req.Request.find);
Could we change the schema for find? Remove the variable find and just have reportType as the top level variable?

2024-04-30 11:10 UTC, akshaypuli commented on src/api/api/BIOMD/BIOMD.js
> +          var year = find.year || null;
Could variable like these be pass-in through a variable called reportSpecs.year?

2024-04-30 11:10 UTC, akshaypuli commented on src/api/services/Communication_Link/middleware.js
Did you intend to make changes to the middleware? Looks like just spaces but want to be careful making changes to this file.

2024-04-30 11:10 UTC, akshaypuli commented on src/api/api/BIOMD/BIOMD.js
Are the following variables GLOBAL definitions or just needed by your API?

2024-05-01 10:00 UTC, oaedward approved these changes

2024-05-01 20:56 UTC, akshaypuli approved these changes

2024-05-01 20:59 UTC, merged