[73] clear content after success and clear button click
Reveal-IQ/MEMS pull request #79
Opened 2023-05-07 01:05 UTC by oaedward

# PR Description
Clear field with the Clear Button in the forms

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2023-05-16 15:13 UTC, akshaypuli requested changes
@oaedward  It looks like most of the country, province and district fields did not clear. Maybe it is the same bug in all the components

2023-05-16 15:13 UTC, akshaypuli commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-MANUFACTURER/MANUFACTURER.vue
The following fields did not clear 
![image](https://github.com/Reveal-IQ/MEMS/assets/8020014/a7b10dc0-bd6e-457f-b409-d839b7ae489f)

2023-05-16 15:13 UTC, akshaypuli commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-MODEL/MODEL.vue
The following field did not clear
![image](https://github.com/Reveal-IQ/MEMS/assets/8020014/b755235e-7fb6-429d-a291-3b62f7b31307)

2023-05-16 15:13 UTC, akshaypuli commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-VENDOR/VENDOR.vue
The following fields did not clear
![image](https://github.com/Reveal-IQ/MEMS/assets/8020014/acd79890-5ffa-4fb6-af42-4495b9cdd8a1)

2023-05-16 15:13 UTC, akshaypuli commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue
The following fields did not clear
![image](https://github.com/Reveal-IQ/MEMS/assets/8020014/9ae4ca22-5d05-4b9b-93c3-dda27ed5387f)

2023-05-16 15:49 UTC, oaedward commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue
I think I know why:
The fields cleared after the Country API was selected as well as all the other APIs. If the content was manually entered into the field, the clear button had no effect. The user had to select from the API options.

I will check on that.

2023-05-16 15:57 UTC, oaedward commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue
All the fields which were unable to clear were tied to the API. Once an object is selected from the options provided by the API, the `clear` button works. 

However, the clear button did not work when the fields received a manual random entry. 

I will check on that, however.

2023-05-16 18:50 UTC, akshaypuli commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue
Can we change those fields to select box or combo box?

2023-05-16 18:59 UTC, oaedward commented on src/client/web/src/components/BIOMD/BIOMD/BIOMD-FACILITY/FACILITY.vue
They are actually combo boxes but if the country list isn't populated into the database, it looks just like a normal input field. 

The district and region fields are also dependent on the country. I think a good implementation will be to disable those fields until a country is selected.

2023-08-27 16:57 UTC, akshaypuli commented
Closing as per discussion on 8/27/2023

2023-08-27 16:57 UTC, closed without merging